name: Runtests
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.6', '1.9']
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: julia-actions/setup-julia@v1.9.2
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@v1.9.2
      - uses: julia-actions/julia-runtest@v1.9.2